# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0013_auto_20160401_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_id', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.URLAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdirector.Campaign')),
            ],
        ),
    ]
