# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdirector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bounces',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='clicks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveries',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
