# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdirector', '0002_auto_20160401_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='openings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
