# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdirector', '0003_delivery_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bounces_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='clicks_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='conversion_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveries_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='openings_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_sent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
