# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdirector', '0004_auto_20160408_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='bounces_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='clicks_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliveries_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='openings_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
