# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdirector', '0006_delivery_openings_percentage_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='openings_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
