# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_urlaccount_active'),
        ('mdirector', '0008_statsdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.IntegerField()),
                ('data_type', models.CharField(max_length=20)),
                ('url_acccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.URLAccount')),
            ],
        ),
    ]
