# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdirector', '0009_dataupdate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataupdate',
            unique_together=set([('url_acccount', 'last_update', 'data_type')]),
        ),
    ]
