# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('id_generated_or_email', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_visited', models.TextField()),
                ('time_remained_seconds', models.CharField(max_length=150)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Visitor')),
            ],
        ),
    ]
