# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_visitortrack_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('kennwort', models.TextField(max_length=100)),
                ('host', models.CharField(max_length=100)),
            ],
        ),
    ]
