# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_connectionurl_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionurl',
            name='host1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionurl',
            name='kennwort_host',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionurl',
            name='user_host',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionurl',
            name='kennwort',
            field=models.TextField(),
        ),
    ]
