# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_visitortrack_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitortrack',
            name='campaign_key',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
