# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_visitortrack_campaign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortrack',
            name='campaign',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitortrack',
            name='campaign_key',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
