# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_auto_20160323_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaccount',
            name='days_tracking_available',
            field=models.IntegerField(default=1),
        ),
    ]
