# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20160328_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortrack',
            name='url_visited',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
