# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_auto_20160328_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortrack',
            name='campaign_key',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
