# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_auto_20160329_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaccount',
            name='_client_key_md',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='urlaccount',
            name='_client_secret_md',
            field=models.TextField(null=True),
        ),
    ]
