# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_auto_20160401_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
