# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_urlaccount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date_update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 10, 53, 20, 488650)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='email_organic_lead',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
