# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0015_auto_20160527_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingVisitorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100)),
                ('name_field_table', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
